config/routes.rb
Rails.application.routes.draw do

  resources :loan_returns, only: [:index] do
    member do
      get :pay_to_admin
      get :loan_received
    end
  end
  resources :bank_accounts
  resources :loans do
    member do
      get :admin_pay
    end
  end
  resources :time_stamps
  resources :plugs
  resources :operations
  resources :non_senses
  resources :why_nots
  resources :revenues
  resources :accounts
  get 'dashboard', to: 'home#index'
  get 'update_status', to: 'loans#update_status'
  resources :users, only: [:index, :show, :new, :edit, :create, :update, :destroy]
  devise_for :users, :controllers => {
    :sessions => "users/sessions",
    :confirmations => "users/confirmations",
    :passwords => "users/passwords",
    :registrations => "users/registrations",
    :unlocks => "users/unlocks",
  }
  devise_scope :user do
    root :to => 'users/sessions#new'
    get "sign_in", to: "users/sessions#new"
    get "sign_up", to: "users/registrations#new"
    get "sign_out", to: "users/sessions#destroy"
  end
end

app/models/plug.rb
class Plug < ApplicationRecord
  after_create -> { update_amount('create') }
  after_destroy -> { update_amount('destroy') }
  validate -> { amount_value }
end

app/controllers/plugs_controller.rb
class PlugsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_plug, only: %i[ show edit update destroy ]

  def index
    @plugs = Plug.all
  end

  def show; end

  def new
    @plug = Plug.new
  end

  def edit; end

  def create
    @plug = Plug.new(plug_params)

    respond_to do |format|
      if @plug.save
        format.html { redirect_to plugs_url, notice: "Plug was successfully created." }
        format.json { render :show, status: :created, location: @plug }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @plug.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @plug.update(plug_params)
        format.html { redirect_to plugs_url, notice: "Plug was successfully updated." }
        format.json { render :show, status: :ok, location: @plug }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @plug.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @plug.destroy
    respond_to do |format|
      format.html { redirect_to plugs_url, notice: "Plug was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_plug
    @plug = Plug.find(params[:id])
  end

  def plug_params
    params.require(:plug).permit(:name, :amount)
  end
end

app/helpers/plugs_helper.rb
module PlugsHelper
end

app/views/plugs/_form.html.erb
<div class="card-body">
<%= form_with(model: plug, local: true) do |form| %>
  <% if plug.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plug.errors.count, "error") %> prohibited this plug from being saved:</h2>

      <ul>
      <% plug.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-group row">
      <label class="col-lg-3 control-label text-lg-right pt-2" for="inputDefault">Description</label>
      <div class="col-lg-6">
        <%= form.text_field :name, :class => 'form-control', :placeholder => "Enter First Description", required: true %>
      </div>
    </div>

    <div class="form-group row">
      <label class="col-lg-3 control-label text-lg-right pt-2" for="inputDefault">Amount</label>
      <div class="col-lg-6">
        <%= form.number_field :amount, :class => 'form-control', :placeholder => "Enter First Amount", required: true %>
      </div>
    </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>
</div>

app/views/plugs/edit.html.erb
<h1>Editing Plug</h1>

<%= render 'form', plug: @plug %>
<br>
<%= link_to 'Show', @plug %> |
<%= link_to 'Back', plugs_path %>

app/views/plugs/index.html.erb
<!doctype html>
<html class="fixed">

<script src="/assets/modernizr.js"></script>
<section role="main" class="content-body">
  <div class="row">
    <div class="col">
      <section class="card">
        <header class="card-header">
          <div class="card-actions">
            <a href="#" class="card-action card-action-toggle" data-card-toggle></a>
            <a href="#" class="card-action card-action-dismiss" data-card-dismiss></a>
          </div>

          <h2 class="card-title">Plugs</h2>
        </header>
        <div class="card-body">
          <%= link_to 'New Plug', new_plug_path, class: 'btn btn-primary' %>
          <p id="notice"><%= notice %></p>
          <table class="table table-bordered table-striped mb-0" id="datatable-default">
            <thead>
            <tr>
              <th>Description</th>
              <th>Amount</th>
              <th>Action</th>
            </tr>
            </thead>
            <tbody>
            <% @plugs.each do |plug| %>
              <tr>
                <td><%= plug.name %></td>
                <td><%= plug.amount %></td>
                <td><%= link_to 'Destroy', plug, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </section>
    </div>
  </div>
</section>
<script src="/assets/theme.js"></script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-42715764-8', 'auto');
  ga('send', 'pageview');
</script>

</html>

app/views/plugs/new.html.erb
<!doctype html>
<html class="fixed">

<script src="/assets/modernizr.js"></script>
<section role="main" class="content-body">
  <div class="row">
    <div class="col">
      <section class="card">
        <header class="card-header">
          <div class="card-actions">
            <a href="#" class="card-action card-action-toggle" data-card-toggle></a>
            <a href="#" class="card-action card-action-dismiss" data-card-dismiss></a>
          </div>

          <h2 class="card-title">New Plug</h2>
        </header>
        <%= render 'form', plug: @plug %>
      </section>
      <br>
      <%= link_to 'Back', plugs_path, class: 'btn btn-default' %>
    </div>
  </div>
</section>

<script src="/assets/theme.js"></script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-42715764-8', 'auto');
  ga('send', 'pageview');
</script>

app/views/plugs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @plug.name %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @plug.amount %>
</p>

<%= link_to 'Edit', edit_plug_path(@plug) %> |
<%= link_to 'Back', plugs_path %>