config/routes.rb
Rails.application.routes.draw do

  resources :loan_returns, only: [:index] do
    member do
      get :pay_to_admin
      get :loan_received
    end
  end
  resources :bank_accounts
  resources :loans do
    member do
      get :admin_pay
    end
  end
  resources :time_stamps
  resources :plugs
  resources :operations
  resources :non_senses
  resources :why_nots
  resources :revenues
  resources :accounts
  get 'dashboard', to: 'home#index'
  get 'update_status', to: 'loans#update_status'
  resources :users, only: [:index, :show, :new, :edit, :create, :update, :destroy]
  devise_for :users, :controllers => {
    :sessions => "users/sessions",
    :confirmations => "users/confirmations",
    :passwords => "users/passwords",
    :registrations => "users/registrations",
    :unlocks => "users/unlocks",
  }
  devise_scope :user do
    root :to => 'users/sessions#new'
    get "sign_in", to: "users/sessions#new"
    get "sign_up", to: "users/registrations#new"
    get "sign_out", to: "users/sessions#destroy"
  end
end

app/models/time_stamp.rb
class TimeStamp < ApplicationRecord
  after_create -> { update_amount('create') }
  after_destroy -> { update_amount('destroy') }
  validate -> { amount_value }
end

app/controllers/time_stamps_controller.rb
class TimeStampsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_time_stamp, only: %i[ show edit update destroy ]

  def index
    @time_stamps = TimeStamp.all
  end

  def show; end

  def new
    @time_stamp = TimeStamp.new
  end

  def edit; end

  def create
    @time_stamp = TimeStamp.new(time_stamp_params)

    respond_to do |format|
      if @time_stamp.save
        format.html { redirect_to time_stamps_url, notice: "Time stamp was successfully created." }
        format.json { render :show, status: :created, location: @time_stamp }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @time_stamp.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @time_stamp.update(time_stamp_params)
        format.html { redirect_to time_stamps_url, notice: "Time stamp was successfully updated." }
        format.json { render :show, status: :ok, location: @time_stamp }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @time_stamp.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @time_stamp.destroy
    respond_to do |format|
      format.html { redirect_to time_stamps_url, notice: "Time stamp was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_time_stamp
    @time_stamp = TimeStamp.find(params[:id])
  end

  def time_stamp_params
    params.require(:time_stamp).permit(:name, :amount)
  end
end

app/helpers/time_stamps_helper.rb
module TimeStampsHelper
end

app/views/time_stamps/_form.html.erb
<div class="card-body">
  <%= form_with(model: time_stamp, local: true) do |form| %>
    <% if time_stamp.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(time_stamp.errors.count, "error") %> prohibited this time_stamp from being saved:</h2>

        <ul>
          <% time_stamp.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group row">
      <label class="col-lg-3 control-label text-lg-right pt-2" for="inputDefault">Description</label>
      <div class="col-lg-6">
        <%= form.text_field :name, :class => 'form-control', :placeholder => "Enter First Description", required: true %>
      </div>
    </div>

    <div class="form-group row">
      <label class="col-lg-3 control-label text-lg-right pt-2" for="inputDefault">Amount</label>
      <div class="col-lg-6">
        <%= form.number_field :amount, :class => 'form-control', :placeholder => "Enter First Amount", required: true %>
      </div>
    </div>

    <div class="actions">
      <%= form.submit class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/time_stamps/edit.html.erb
<h1>Editing Time Stamp</h1>

<%= render 'form', time_stamp: @time_stamp %>
<br>
<%= link_to 'Show', @time_stamp %> |
<%= link_to 'Back', time_stamps_path %>

app/views/time_stamps/index.html.erb
<!doctype html>
<html class="fixed">

<script src="/assets/modernizr.js"></script>
<section role="main" class="content-body">
  <div class="row">
    <div class="col">
      <section class="card">
        <header class="card-header">
          <div class="card-actions">
            <a href="#" class="card-action card-action-toggle" data-card-toggle></a>
            <a href="#" class="card-action card-action-dismiss" data-card-dismiss></a>
          </div>

          <h2 class="card-title">Time Stamps</h2>
        </header>
        <div class="card-body">
          <%= link_to 'New Time Stamp', new_time_stamp_path, class: 'btn btn-primary' %>
          <p id="notice"><%= notice %></p>
          <table class="table table-bordered table-striped mb-0" id="datatable-default">
            <thead>
            <tr>
              <th>Description</th>
              <th>Amount</th>
              <th>Action</th>
            </tr>
            </thead>
            <tbody>
            <% @time_stamps.each do |time_stamp| %>
              <tr>
                <td><%= time_stamp.name %></td>
                <td><%= time_stamp.amount %></td>
                <td><%= link_to 'Destroy', time_stamp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </section>
    </div>
  </div>
</section>
<script src="/assets/theme.js"></script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-42715764-8', 'auto');
  ga('send', 'pageview');
</script>

</html>

app/views/time_stamps/new.html.erb
<!doctype html>
<html class="fixed">

<script src="/assets/modernizr.js"></script>
<section role="main" class="content-body">
  <div class="row">
    <div class="col">
      <section class="card">
        <header class="card-header">
          <div class="card-actions">
            <a href="#" class="card-action card-action-toggle" data-card-toggle></a>
            <a href="#" class="card-action card-action-dismiss" data-card-dismiss></a>
          </div>

          <h2 class="card-title">New Time Stamp</h2>
        </header>
        <%= render 'form', time_stamp: @time_stamp %>
      </section>
      <br>
      <%= link_to 'Back', time_stamps_path, class: 'btn btn-default' %>
    </div>
  </div>
</section>

<script src="/assets/theme.js"></script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-42715764-8', 'auto');
  ga('send', 'pageview');
</script>

app/views/time_stamps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @time_stamp.name %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @time_stamp.amount %>
</p>

<%= link_to 'Edit', edit_time_stamp_path(@time_stamp) %> |
<%= link_to 'Back', time_stamps_path %>